services:
  backend:
    image: python:3.12
    container_name: backend
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    working_dir: /app
    volumes:
      - ./backend:/app:cached
    command: fastapi run app/main.py --port 8000 --reload
    ports:
      - "8000:8000"
    depends_on:
      - database

  database:
    image: mongo:8.0.0
    container_name: mongo
    build:
      context: .
      dockerfile: ./docker/mongo/Dockerfile
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: