# Use the official MongoDB image as the base image
FROM mongo:latest

# Copy the initialization script into the container's /docker-entrypoint-initdb.d directory
COPY mongo-init /docker-entrypoint-initdb.d/